import React, { Component } from 'react';
import { ListViewCard } from '../Common';

const MOCK_DATA = [
  {
    lecture: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'LE',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: '',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: 'EN',
      gradeOption: 'L',
      creditHours: 4,
      gradeOptionPlus: true,
      creditHoursPlus: false,
      courseTitle: 'Practicum in Pro Web Design',
      enrollmentCapacity: 60,
      enrollmentQuantity: 64,
      countOnWaitlist: 2,
      stopEnrollmentFlag: true,
      classTimes: [
        {
          dayCode: '2',
          startDate: 1585551600000,
          beginHHTime: '14',
          beginMMTime: '0',
          endHHTime: '15',
          endMMTime: '20',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: '2019-03-15',
        },
        {
          dayCode: '4',
          startDate: 1585551600000,
          beginHHTime: '14',
          beginMMTime: '0',
          endHHTime: '15',
          endMMTime: '20',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: '2019-03-15',
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
    final: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'LE',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: 'FI',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: null,
      gradeOption: null,
      creditHours: null,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: null,
      enrollmentCapacity: null,
      enrollmentQuantity: null,
      countOnWaitlist: null,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '4',
          startDate: 1585551600000,
          beginHHTime: '15',
          beginMMTime: '0',
          endHHTime: '17',
          endMMTime: '59',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: null,
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
    discussion: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'DI',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: '',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: null,
      gradeOption: null,
      creditHours: null,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: null,
      enrollmentCapacity: null,
      enrollmentQuantity: null,
      countOnWaitlist: null,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '2',
          startDate: 1585551600000,
          beginHHTime: '11',
          beginMMTime: '0',
          endHHTime: '11',
          endMMTime: '50',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: null,
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
  },
  {
    lecture: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'LE',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: '',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: 'EN',
      gradeOption: 'L',
      creditHours: 4,
      gradeOptionPlus: true,
      creditHoursPlus: false,
      courseTitle: 'Practicum in Pro Web Design',
      enrollmentCapacity: 60,
      enrollmentQuantity: 64,
      countOnWaitlist: 2,
      stopEnrollmentFlag: true,
      classTimes: [
        {
          dayCode: '2',
          startDate: 1585551600000,
          beginHHTime: '14',
          beginMMTime: '0',
          endHHTime: '15',
          endMMTime: '20',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: '2019-03-15',
        },
        {
          dayCode: '4',
          startDate: 1585551600000,
          beginHHTime: '14',
          beginMMTime: '0',
          endHHTime: '15',
          endMMTime: '20',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: '2019-03-15',
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
    final: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'LE',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: 'FI',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: null,
      gradeOption: null,
      creditHours: null,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: null,
      enrollmentCapacity: null,
      enrollmentQuantity: null,
      countOnWaitlist: null,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '4',
          startDate: 1585551600000,
          beginHHTime: '15',
          beginMMTime: '0',
          endHHTime: '17',
          endMMTime: '59',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: null,
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
    discussion: {
      subjectCode: 'COGS',
      courseCode: '187B',
      instructionType: 'DI',
      sectionNumber: '960510',
      sectionCode: 'A00',
      specialMeetingCode: '',
      longDescription: '',
      sectionStatus: null,
      enrollmentStatus: null,
      gradeOption: null,
      creditHours: null,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: null,
      enrollmentCapacity: null,
      enrollmentQuantity: null,
      countOnWaitlist: null,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '2',
          startDate: 1585551600000,
          beginHHTime: '11',
          beginMMTime: '0',
          endHHTime: '11',
          endMMTime: '50',
          buildingCode: 'HSS',
          roomCode: '1346',
          endDate: null,
        },
      ],
      instructors: [
        'Kirsh, David Joel',
      ],
    },
  },
  {
    discussion: {
      subjectCode: 'LTEA',
      courseCode: '120A',
      instructionType: 'LA',
      sectionNumber: '2064',
      sectionCode: 'A01',
      specialMeetingCode: null,
      longDescription: '',
      enrollmentStatus: 'EN',
      gradeOption: 'P',
      creditHours: 4,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: 'Chinese Films',
      enrollmentCapacity: 320,
      enrollmentQuantity: 308,
      countOnWaitlist: 1,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '1',
          startDate: 1585551600000,
          beginHHTime: 17,
          beginMMTime: 0,
          endHHTime: 19,
          endMMTime: 50,
          buildingCode: '',
          roomCode: '',
          endDate: null,
        },
      ],
      instructors: [
        'Zhang, Yingjin',
      ],
    },
    lecture: {
      subjectCode: 'LTEA',
      courseCode: '120A',
      instructionType: 'LE',
      sectionNumber: '2063',
      sectionCode: 'A00',
      specialMeetingCode: '',
      longDescription: 'Visions of the City',
      enrollmentStatus: 'EN',
      gradeOption: 'P',
      creditHours: 4,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: 'Chinese Films',
      enrollmentCapacity: 320,
      enrollmentQuantity: 308,
      countOnWaitlist: 1,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '1',
          startDate: 1585551600000,
          beginHHTime: 17,
          beginMMTime: 0,
          endHHTime: 19,
          endMMTime: 50,
          buildingCode: '',
          roomCode: '',
          endDate: null,
        },
      ],
      instructors: [
        'Zhang, Yingjin',
      ],
    },
    final: {
      subjectCode: 'LTEA',
      courseCode: '120A',
      instructionType: 'LE',
      sectionNumber: '2063',
      sectionCode: 'A00',
      specialMeetingCode: 'FI',
      longDescription: 'Visions of the City',
      enrollmentStatus: null,
      gradeOption: null,
      creditHours: null,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: null,
      enrollmentCapacity: null,
      enrollmentQuantity: null,
      countOnWaitlist: null,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '5',
          startDate: 1591945200000,
          beginHHTime: 19,
          beginMMTime: 0,
          endHHTime: 21,
          endMMTime: 59,
          buildingCode: '',
          roomCode: '',
          endDate: null,
        },
      ],
      instructors: [
        'Zhang, Yingjin',
      ],
    },
  },
  {
    lecture: {
      subjectCode: 'PHIL',
      courseCode: '27',
      instructionType: 'LE',
      sectionNumber: '5027',
      sectionCode: 'A02',
      specialMeetingCode: '',
      longDescription: '',
      enrollmentStatus: 'EN',
      gradeOption: 'P',
      creditHours: 4,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: 'Ethics And Society',
      enrollmentCapacity: 37,
      enrollmentQuantity: 39,
      countOnWaitlist: 2,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '1',
          startDate: 1585551600000,
          beginHHTime: 14,
          beginMMTime: 0,
          endHHTime: 14,
          endMMTime: 50,
          buildingCode: '',
          roomCode: '',
          endDate: 1591340400000,
        },
      ],
      instructors: [
        'Brandt, Reuven A',
      ],
    },
    discussion: {
      subjectCode: 'PHIL',
      courseCode: '27',
      instructionType: 'DI',
      sectionNumber: '5027',
      sectionCode: 'A02',
      specialMeetingCode: '',
      longDescription: '',
      enrollmentStatus: 'EN',
      gradeOption: 'P',
      creditHours: 4,
      gradeOptionPlus: false,
      creditHoursPlus: false,
      courseTitle: 'Ethics And Society',
      enrollmentCapacity: 37,
      enrollmentQuantity: 39,
      countOnWaitlist: 2,
      stopEnrollmentFlag: false,
      classTimes: [
        {
          dayCode: '1',
          startDate: 1585551600000,
          beginHHTime: 14,
          beginMMTime: 0,
          endHHTime: 14,
          endMMTime: 50,
          buildingCode: '',
          roomCode: '',
          endDate: 1591340400000,
        },
      ],
      instructors: [
        'Brandt, Reuven A',
      ],
    },
  },
];

class ListView extends Component {
  constructor(props) {
    super(props);
    this.state = {
    };
  }

  render() {
    return (
      <div>
        {MOCK_DATA.map((d) => (
          <ListViewCard
            lecture={d.lecture}
            discussion={d.discussion}
            final={d.final}
          />
        ))}
      </div>
    );
  }
}

export default ListView;
